export * from './propsInterface/account'
export * from './propsInterface/authProps'
export * from './propsInterface/error'
export * from './propsInterface/board'
export * from './reducerInterface/drawReducer'
export * from './socketInterface/socketInterface'